version: '3.3'
services:
  postgres:
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=mirror_db_user
      - POSTGRES_PASSWORD=mirror_db_pass
    volumes:
      - "${PWD}/mirror:/mirror"
    image: postgres:alpine
  sb-mirror:
    image: mchangrh/sb-mirror:latest
    # map port externally
    ports:
      - "873:873"
    environment:
      - MIRROR=TRUE
    volumes:
      - "${PWD}/mirror:/mirror"