version: '3'
services:
    image: mchangrh/sb-mirror:latest
    # map port externally
    ports:
      - "873:873"
    environment:
      # auto generate .db in /export
      - SQLITE=FALSE
      - MIRROR=TRUE
      # override to set upstream mirror, defaults to sponsor.ajay.app
      #- MIRROR_URL=sb.mirror.example.com
    volumes:
      - ./mirror:/mirror
      - ./export:/export