version: '3.3'
services:
  postgres:
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=mirror_db_user
      - POSTGRES_PASSWORD=mirror_db_pass
    volumes:
      - "${PWD}/mirror:/mirror"
    image: postgres:alpine
  sb-mirror:
    image: mchangrh/sb-mirror:latest
    build: ./sb-mirror
    # map port externally
    ports:
      - "873:873"
    environment:
      # - MIRROR=TRUE # enable cronjob
      # - MIRROR_URL=qc.mchang.xyz # override to set upstream mirror, defaults to sponsor.ajay.app
      # - SQLITE=FALSE # generate .db in /export
    volumes:
      - "${PWD}/mirror:/mirror"
      - "${PWD}/export:/export"
  sb-server:
    ports: "8080:8080"
    environment:
      volumes:
        - "${PWD}/export/SponsorTimesDB.db:/app/database/SponsorTimesDB.db"
        - "${PWD}/config.json:/app/config.json"
    image: mchangrh/sb-server-runner:latest
    build: ./sb-server-runner