name: rsync-debian
on:
  push:
    branches:
      - main
    paths:
      - build/rsync/**

jobs:
  build-rsync-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
	      id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            mchangrh/rsync
            ghcr.io/mchangrh/rsync
          tags: |
            type=sha,
			      type-raw,value=debian
          flavor: |
            latest=true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build rsync-debian
        uses: docker/build-push-action@v2
        with:
          context: ./build/rsync
          push: true
          tags: ${{ steps.meta.outputs.tags }}