name: sb-mirror-alpine
on:
  push:
    branches:
      - main
    paths:
      - build/sb-mirror.alpine/**
  workflow_dispatch:

jobs:
  build-sb-mirror-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            mchangrh/sb-mirror
            ghcr.io/mchangrh/sb-mirror
          tags: |
            type-raw,value=alpine
          flavor: |
            latest=false
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build sb-mirror-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./build/sb-mirror.alpine
          push: true
          tags: ${{ steps.meta.outputs.tags }}