name: rsync
on:
  push:
    branches:
      - main
    paths:
      - build/rsync/**
  workflow_dispatch:

jobs:
  build:
    uses: mchangrh/sb-mirror/.github/workflows/docker-build.yml@main
    with:
      name: "rsync"
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}